AnimatiWA/AnimatiApp

- AnimatiApp Android/app/src/main/AndroidManifest.xml
Permiso en AndroidManifest para acceder a internet
> Se agrega permiso para acceder a internet

- AnimatiApp Android/app/src/main/AndroidManifest.xml
Eliminación de la página de navegación y agregado de la página login como primera página de la aplicación
> Actualización del manifest

- AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/SobreNosotrosActivity.java
- AnimatiApp Android/app/src/main/res/drawable/gradient_pink.xml
- AnimatiApp Android/app/src/main/res/layout/activity_sobre_nosotros.xml
Rediseño del layout sobre nosotros
> Actualización del layout de Sobre Nosotros

- AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/CartActivity.java
Se borran comentarios innescesariosiliarice con la librería Volley
> Se borran comentarios innescesarios

- AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/Gallery.java
- AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/LoginActivity.java
> Correcciones de ultimo momento

- AnimatiApp Android/app/src/main/AndroidManifest.xml
- AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/ForgotPasswordActivity.java
- AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/RecoveryPasswordActivity.java
- AnimatiApp Android/app/src/main/res/layout/activity_recovery_password.xml
- AnimatiApp Android/app/src/main/res/values/strings.xml
- AnimatiApp Django/AnimatiBack/AnimatiApp/serializers.py
- AnimatiApp Django/AnimatiBack/AnimatiApp/urls.py
- AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
RecoveryPassword: Se retira endpoint y vistas no funcionales del back / Se suma botón retorno a inicio a la vista / Registro en AndroidManifest. 
- Este PR incluye la integración de envíos de mail funcionales por ForgotPassword.
- Botón de regreso en RecoveryPassword testeado, redirige a Login.
- Se incorpora la vista Recovery a modo DEMOSTRATIVO, solo en caso de pedido por los tutores. Los campos para cambiar la pass no son funcionales.
> Modificaciones vista RecoveryPassword / Limpieza de líneas de código en back no funcionales vinculadas.

- AnimatiApp Android/app/src/main/AndroidManifest.xml
- AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/RecoveryPasswordActivity.java
- AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/activity_inicio.java
- AnimatiApp Android/app/src/main/res/drawable/rect_button_background.xml
- AnimatiApp Android/app/src/main/res/layout/activity_inicio.xml
- AnimatiApp Android/app/src/main/res/values/strings.xml
Se añade button en "inicio" enlazado a vista "profile". / Vista "recovery_pass"  incluye parámetros para creación de nueva clave.
> Funcionalidad "Mis datos" para ingreso a Profile.

- AnimatiApp Android/app/src/main/res/layout/activity_login.xml
Se quita propiedad  "Gone" del button. De no agregar funcionalidad, mantener como bug.
> Se visibiliza button en Login: "Olvidaste Contraseña?".

- AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/CartActivity.java
- AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/Product.java
- AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/ProductListAdapter.java
- AnimatiApp Android/app/src/main/res/layout/cart_product_item_list.xml
- AnimatiApp Android/app/src/main/res/values/strings.xml
- AnimatiApp Django/AnimatiBack/AnimatiApp/urls.py
- AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
Se agrega funcionalidad para eliminar elementos del carrito de a una unidad. Se rediseña el carrito para mostrar mas cómodamente los datos de cada producto.
> Funcionalidad de borrar una unidad del carrito

- AnimatiApp Android/app/src/main/res/layout/activity_forgot_pass_email.xml
- AnimatiApp Android/app/src/main/res/layout/activity_recovery_password.xml
- AnimatiApp Android/app/src/main/res/values/colors.xml
- AnimatiApp Android/app/src/main/res/values/strings.xml
**VISUALIZACIÓN:**
Mismo proceso en la otra vista, permite loguear luego del cambio de contraseña.
> Cambio aspecto visual recuperación pass y cambio pass.

- AnimatiApp Android/app/src/main/res/layout/activity_forgot_pass_email.xml
- AnimatiApp Android/app/src/main/res/layout/activity_recovery_password.xml
Se revierten cambios a activity_forgot_pass_email.xml y se oculta botón de logout erroneamente implementado en activity_recovery_password.xml
> Se revierten cambios

- AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
Se modifica vista productoCarrito/crear para que reciba la referncia al carrito faltante
> Corrección endpoint productoCarrito/crear

- AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
Se vuelve a corregir el endpoint proructoCarrito/crear
> Se vuelve a corregir el endpoint proructoCarrito/crear

- AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
- AnimatiApp Django/AnimatiBack/AnimatiCrud/settings.py
Modificaciones a vistas del back y config de django
> Modificaciones a vistas del back y config de django

- AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
Se vuelve a modificar endpoint de contacto
> Se vuelve a modificar endpoint de contacto

- AnimatiApp Django/AnimatiBack/AnimatiApp/serializers.py
- AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
Se modifica endpoint para recibir la imagen de los productos de un carrito
> Se modifica endpoint para recibir la imagen de los productos de un carrito

- AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/ForgotPasswordActivity.java
- AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/ProfileActivity.java
- AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/RecoveryPasswordActivity.java
Se corrigen llamadas a endpoints para adaptarlas a las modificaciones del sprint 1 del proyecto de prácticas profesionalizantes.
> Readaptacion de llamadas a endpoints

- AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
Se corrige endpoint del historial de compras
> Se corrige endpoint del historial de compras

- AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
Se modifican vistas para que devuelvan la fecha de deshabilitación de cada carrito directamente. Se simplifica endpoint del historial de compras
> Corrección fechas en endpoints de carrito.

- AnimatiApp Android/app/src/main/AndroidManifest.xml
- AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/ModifyProfileActivity.java
- AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/ProfileActivity.java
- AnimatiApp Android/app/src/main/res/layout/activity_modify_profile.xml
- AnimatiApp Android/app/src/main/res/layout/activity_profile.xml
- AnimatiApp Android/app/src/main/res/values/strings.xml
Se genera pantalla para modificación de perfil de usuario con su lógica
> Yasmin burrut
